version: "3.5"

services:
    application:
        container_name: "${APPLICATION_CONTAINER_NAME:-glpi}"
        restart: "${APPLICATION_CONTAINER_RESTART_POLICY:-unless-stopped}"
        build:
            context: "containers/glpi"
            args:
                BASE_IMAGE: "${APPLICATION_CONTAINER_BASE_IMAGE:-php:apache-buster}"
                HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
                HOST_USER_ID: "${HOST_USER_ID:-1000}"
        networks:
            default:
                aliases:
                    - "${APPLICATION_NETWORK_ALIAS:-glpi.local}"
        ports:
            - "${APPLICATION_HTTP_PORT:-80}:80"
        volumes:
            - type: "bind"
              source: "${APPLICATION_PATH:-./mounts/application/var/www/glpi}"
              target: "/var/www/glpi"

networks:
    default:
        driver: "bridge"
        name: "${NETWORK_NAME:-glpi_bridge}"
