version: "3.5"

services:
    adminer:
        image: "adminer"
        restart: "${UTILITIES_CONTAINERS_RESTART_POLICY:-unless-stopped}"
        ports:
            - "8080:8080"
    mail:
        image: "msztolcman/sendria:v2.2.2.0"
        restart: "${UTILITIES_CONTAINERS_RESTART_POLICY:-unless-stopped}"
        ports:
            - "1025:1025"
            - "8025:1080"
    memcached:
        image: "memcached"
        restart: "${UTILITIES_CONTAINERS_RESTART_POLICY:-unless-stopped}"
    openldap:
        image: "osixia/openldap"
        environment:
            LDAP_DOMAIN: "glpi.org"
        restart: "${UTILITIES_CONTAINERS_RESTART_POLICY:-unless-stopped}"
    phpldapadmin:
        image: "osixia/phpldapadmin"
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "openldap"
        ports:
            - "8443:443"
        restart: "${UTILITIES_CONTAINERS_RESTART_POLICY:-unless-stopped}"
    redis:
        image: "redis"
        restart: "${UTILITIES_CONTAINERS_RESTART_POLICY:-unless-stopped}"

networks:
    default:
        driver: "bridge"
        name: "${NETWORK_NAME:-glpi_bridge}"
